### ISSUE TITLE
CTC on AWS

### ISSUE THREAD

**Issue by snev10** [sherjilozair/ctc#7]
Hi,

I'm trying to install ctc on an AWS instance with gpu (p2.xlarge). Ubuntu 14.04.
I have installed warp_ctc and successfully run test_gpu and  test_cpu.

After running 

`sudo python setup.py install
`

I get the following error: 

```
ubuntu@ip-172-31-21-85:~/ctc/examples$ python simple.py 
Traceback (most recent call last):
  File "simple.py", line 1, in <module>
    from ctc import cpu_ctc_th, cpu_ctc_np
  File "/usr/local/lib/python2.7/dist-packages/ctc/__init__.py", line 1, in <module>
    from .ctc import cpu_ctc_np, cpu_ctc_th
  File "/usr/local/lib/python2.7/dist-packages/ctc/ctc.py", line 18, in <module>
    libwarpctc = npct.load_library(os.path.join(os.path.dirname(__file__), "../build/libwarpctc.{}".format(ext)), "")
  File "/usr/local/lib/python2.7/dist-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
ubuntu@ip-172-31-21-85:~/ctc/examples$ 
```

Any ideas on how to fix this? I have printed 

`os.path.dirname(__file__)
`

and it is empty.
Thanks!

**Comment by mindhash** [comment]
Its probably late but I just wanted to share how i faced a similar issue.

This issue occurred when I did not run make. If you check your repo dir (/ctc) and don't find either libwarpctc.dylib or libwarpctc.so would mean you have not run make yet. 
Follow the install steps again to fix the issue.
